# Generated by Django 3.2.15 on 2022-09-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('1', '手持机'), ('2', '平板电脑'), ('3', '笔记本'), ('4', '防爆平板'), ('5', '其他')], max_length=10)),
                ('size', models.CharField(choices=[('1', '4英寸'), ('2', '5英寸'), ('3', '6英寸'), ('4', '7英寸'), ('5', '8英寸'), ('6', '10.1英寸'), ('7', '12.2英寸'), ('8', '13.3英寸'), ('9', '14英寸'), ('10', '15.6英寸'), ('11', '21.5英寸')], max_length=10)),
                ('platform', models.CharField(choices=[('1', 'Android'), ('2', 'windows')], max_length=10)),
                ('function', models.CharField(choices=[('1', 'HF RFID'), ('2', '条码扫描 '), ('3', 'UHF RFID'), ('4', 'LF RFID '), ('5', 'NFC'), ('6', '指纹识别'), ('7', 'GPS  '), ('8', '摄像头'), ('9', '身份证识别')], max_length=10)),
            ],
        ),
    ]
