# Generated by Django 3.2.15 on 2022-09-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('4', '4英寸'), ('5', '5英寸'), ('6', '6英寸'), ('7', '7英寸'), ('8', '8英寸'), ('10.1', '10.1英寸'), ('12.2', '12.2英寸'), ('13.3', '13.3英寸'), ('14', '14英寸'), ('15.6', '15.6英寸'), ('21.5', '21.5英寸')], max_length=10),
        ),
    ]
