# Generated by Django 3.2.15 on 2023-02-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainIMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ImageField(upload_to='img')),
            ],
        ),
    ]
